name: docker-builds
on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: main-app
            dockerfile: ./Dockerfile
            context: .
          - name: worker
            dockerfile: ./workers/proctor/Dockerfile
            context: ./workers/proctor
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build ${{ matrix.name }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: false
          tags: ${{ matrix.name }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max 