name: python-tests
on: [push, pull_request]

jobs:
  py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - name: Install
        run: pip install -r workers/proctor/requirements-dev.txt
      - name: Pytest
        run: pytest workers/proctor/ -q 