name: publish-worker-image

on:
  push:
    tags:
      - 'v*.*.*'      # semantic version tags trigger a publish

permissions:
  contents: read
  packages: write      # needed for GHCR

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1️⃣  Set up Docker Buildx
      - uses: docker/setup-buildx-action@v3

      # 2️⃣  Log in to GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      # 3️⃣  Build the worker image and push two tags: the version and "latest"
      - name: Build & push worker image
        uses: docker/build-push-action@v5
        with:
          context: ./workers/proctor
          file: ./workers/proctor/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/worker:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/worker:latest 